# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [1]:
# H0: dragon_type_hp_mean <= grass_type_hp_mean
# H1: dragon_type_hp_mean > grass_type_hp_mean

In [5]:
dragon_hp = df[df["Type 1"] == "Dragon"]["HP"]
grass_hp = df[df["Type 1"] == "Grass"]["HP"]

In [6]:
st.ttest_ind(dragon_hp, grass_hp, alternative = "greater")

# the p_value is smaller than 0.05, which means it is actually so improbable that was just by chance that there has to be a reason behind that.
# so we can accept our alternative hypothesis.

TtestResult(statistic=np.float64(3.590444254130357), pvalue=np.float64(0.0002567969150153481), df=np.float64(100.0))

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
# H0: legen_stats = no_legen_stats
# H1: legen_stats != no_legen_stats

In [11]:
legen_stats = df[df["Legendary"] == True][["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]]
no_legen_stats = df[df["Legendary"] == False][["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]]

In [13]:
st.ttest_ind(legen_stats, no_legen_stats, alternative = "two-sided")
# we want to know if the stats are different so now the it is a two tails test
# all the p-values are super tiny so we can reject the null hypotehesis

TtestResult(statistic=array([ 8.03612441, 10.39732102,  7.18124012, 14.19140621, 11.03775106,
        9.76523433]), pvalue=array([3.33064768e-15, 7.82725300e-24, 1.58422261e-12, 6.31491577e-41,
       1.84398096e-26, 2.35407544e-21]), df=array([798., 798., 798., 798., 798., 798.]))

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [14]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [15]:
import math

In [34]:
def euclidean_dist (df):
    school_coordinates = (-118, 34)
    hospital_coordinates = (-122, 37)
    euc_dist_from_school = []
    euc_dist_from_hospital = []
    for i in df.index:
        euc_dist_from_school.append(math.dist((df.loc[i]["longitude"], df.loc[i]["latitude"]), school_coordinates))
        euc_dist_from_hospital.append(math.dist((df.loc[i]["longitude"], df.loc[i]["latitude"]), hospital_coordinates))
    df["euc_dist_from_school"] = euc_dist_from_school
    df["euc_dist_from_hospital"] = euc_dist_from_hospital
    return df

df = euclidean_dist(df)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,euc_dist_from_school,euc_dist_from_hospital
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508

In [42]:
close_from_home = df[(df["euc_dist_from_school"] < 0.5) | (df["euc_dist_from_hospital"] < 0.5)]
far_from_home = df[(df["euc_dist_from_school"] >= 0.5) | (df["euc_dist_from_hospital"] >= 0.5)]

In [ ]:
# We posit that houses close to either a school or a hospital are more expensive.
# H0: close_from_home_price <= far_from_home_price
# H1: close_from_home_price > far_from_home_price

In [48]:
st.ttest_ind(close_from_home["median_house_value"], far_from_home["median_house_value"], alternative = "greater")

# the p_value is less than 0.05, so we can reject the null hypothesis and accept the alternative hypothesis

TtestResult(statistic=np.float64(24.10661246598843), pvalue=np.float64(3.5240298270496207e-127), df=np.float64(23827.0))